package Mojo::Autotask::Backend::Pg;
use Mojo::Base 'Mojo::Autotask::Backend';

use Carp 'croak';
use Mojo::IOLoop;
use Mojo::Pg 4.0;

has 'pg';

sub delete {
  my ($self, $entity) = (shift, shift);
  $self->pg->db->delete($self->table->{$entity}, @_);
}

sub insert {
  my ($self, $entity) = (shift, shift);
  $self->pg->db->insert($self->table->{$entity}, @_);
}

sub last_modified {
  my ($self, $entity, $id) = @_;
  return unless $entity;
  if ( $id ) {
    return @{$self->pg->db->query(sprintf(q(select id,extract('epoch' from "local_lastmodified") as "local_lastmodified" from "%s" where id=$1), $self->table->{$entity}), $id)->array};
  } else {
    return @{$self->pg->db->query(sprintf(q(select id,extract('epoch' from "local_lastmodified") as "local_lastmodified" from "%s" order by local_lastmodified desc limit 1), $self->table->{$entity}))->array};
  }
}

sub new {
  my ($self, $dsn) = (shift, shift);
  $self = $self->SUPER::new(pg => Mojo::Pg->new($dsn), @_);

  my $db = Mojo::Pg->new($dsn)->db;
  croak 'PostgreSQL 9.6 or later is required'
    if $db->dbh->{pg_server_version} < 90600;
  $db->disconnect;

  $self->pg->auto_migrate(1)->migrations->name('autotask')->from_data;

  my $table_prefix = $self->table_prefix;
  $self->table({map { /^(\w+)\."$table_prefix(\w+)"$/; $2 => "$table_prefix$2" } grep { /^(\w+)\."$table_prefix(\w+)"$/ } $self->pg->db->dbh->tables('public')}) if $self->pg;

  return $self;
}

sub select {
  my ($self, $entity) = (shift, shift);
  $self->pg->db->select($self->table->{$entity}, @_);
}

sub update {
  my ($self, $entity) = (shift, shift);
  $self->pg->db->update($self->table->{$entity}, @_);
}

1;

__DATA__

@@ autotask

-- 1 up
create table "at_Account" ("Active" boolean, "AdditionalAddressInformation" varchar(100), "Address1" varchar(128), "Address2" varchar(128), "AlternatePhone1" varchar(25), "AlternatePhone2" varchar(25), "AssetValue" real, "BillToAdditionalAddressInformation" varchar(100), "BillToAddress1" varchar(150), "BillToAddress2" varchar(150), "BillToAddressToUse" integer, "BillToAttention" varchar(50), "BillToCity" varchar(50), "BillToCountryID" integer, "BillToState" varchar(128), "BillToZipCode" varchar(50), "City" varchar(30), "id" integer primary key, "AccountName" varchar(100), "AccountNumber" varchar(50), "OwnerResourceID" integer, "ClientPortalActive" boolean, "AccountType" smallint, "CompetitorID" integer, "Country" varchar(100), "CountryID" integer, "CreateDate" timestamp without time zone, "CurrencyID" integer, "Fax" varchar(25), "InvoiceEmailMessageID" integer, "InvoiceTemplateID" integer, "InvoiceNonContractItemsToParentAccount" boolean, "KeyAccountIcon" integer, "LastActivityDate" timestamp without time zone, "MarketSegmentID" integer, "ParentAccountID" integer, "Phone" varchar(25), "QuoteEmailMessageID" integer, "QuoteTemplateID" integer, "SICCode" varchar(32), "State" varchar(40), "StockMarket" varchar(10), "StockSymbol" varchar(10), "TaskFireActive" boolean, "TaxExempt" boolean, "TaxID" varchar(50), "TaxRegionID" integer, "TerritoryID" integer, "InvoiceMethod" integer, "WebAddress" varchar(255), "PostalCode" varchar(10), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AccountAlert" ("id" integer primary key, "AlertText" varchar(8000), "AlertTypeID" integer, "AccountID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AccountLocation" ("AccountID" integer, "id" integer primary key, "LocationName" varchar(100), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AccountNote" ("AssignedResourceID" integer, "AccountID" integer, "id" integer primary key, "ContactID" integer, "CompletedDateTime" timestamp without time zone, "LastModifiedDate" timestamp without time zone, "Note" varchar(32000), "EndDateTime" timestamp without time zone, "Name" varchar(128), "OpportunityID" integer, "StartDateTime" timestamp without time zone, "ActionType" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AccountTeam" ("AccountID" bigint, "id" integer primary key, "ResourceID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AccountToDo" ("ActionType" integer, "AssignedToResourceID" bigint, "AccountID" bigint, "id" integer primary key, "CompletedDate" timestamp without time zone, "ContactID" bigint, "ContractID" bigint, "CreateDateTime" timestamp without time zone, "CreatorResourceID" bigint, "ActivityDescription" varchar(32000), "EndDateTime" timestamp without time zone, "LastModifiedDate" timestamp without time zone, "OpportunityID" bigint, "StartDateTime" timestamp without time zone, "TicketID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ActionType" ("id" integer primary key, "Active" boolean, "Name" varchar(32), "SystemActionType" boolean, "View" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AdditionalInvoiceFieldValue" ("AdditionalInvoiceFieldID" bigint, "id" integer primary key, "InvoiceBatchID" bigint, "FieldValue" varchar(100), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AllocationCode" ("Active" boolean, "id" integer primary key, "AllocationCodeType" integer, "Department" integer, "Description" varchar(500), "GeneralLedgerCode" integer, "IsExcludedFromNewContracts" boolean, "MarkupRate" real, "Name" varchar(200), "ExternalNumber" varchar(100), "TaxCategoryID" integer, "Taxable" boolean, "Type" integer, "UnitCost" real, "UnitPrice" real, "UseType" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Appointment" ("id" integer primary key, "Title" varchar(256), "CreateDateTime" timestamp without time zone, "CreatorResourceID" integer, "Description" varchar(8000), "EndDateTime" timestamp without time zone, "ResourceID" integer, "StartDateTime" timestamp without time zone, "UpdateDateTime" timestamp without time zone, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_AttachmentInfo" ("AttachDate" timestamp without time zone, "AttachedByContactID" bigint, "AttachedByResourceID" bigint, "id" integer primary key, "ContentType" varchar(100), "FullPath" varchar(255), "FileSize" bigint, "OpportunityID" bigint, "ParentID" bigint, "ParentType" integer, "Publish" integer, "Title" varchar(255), "Type" varchar(30), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_BillingItem" ("AccountManagerWhenApprovedID" integer, "AllocationCodeID" integer, "ApprovedTime" timestamp without time zone, "id" integer primary key, "AccountID" integer, "ContractCostID" bigint, "ContractID" integer, "Description" varchar(2000), "ExpenseItemID" integer, "ExtendedPrice" real, "InstalledProductID" bigint, "InternalCurrencyExtendedPrice" real, "InternalCurrencyRate" real, "InternalCurrencyTaxDollars" real, "InternalCurrencyTotalAmount" real, "LineItemID" bigint, "InvoiceID" integer, "ItemApproverID" integer, "ItemDate" timestamp without time zone, "ItemName" varchar(255), "LineItemFullDescription" varchar(8000), "LineItemGroupDescription" varchar(8000), "MilestoneID" bigint, "NonBillable" integer, "OurCost" real, "ProjectCostID" bigint, "ProjectID" integer, "Quantity" real, "Rate" real, "RoleID" integer, "ServiceBundleID" bigint, "ServiceID" bigint, "SubType" integer, "TaskID" integer, "TaxDollars" real, "TicketCostID" bigint, "TicketID" integer, "TimeEntryID" integer, "TotalAmount" real, "Type" integer, "VendorID" bigint, "WebServiceDate" timestamp without time zone, "PurchaseOrderNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_BillingItemApprovalLevel" ("ApprovalDateTime" timestamp without time zone, "ApprovalLevel" integer, "ApprovalResourceID" integer, "id" integer primary key, "TimeEntryID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ChangeRequestLink" ("id" integer primary key, "ChangeRequestTicketID" integer, "ProblemOrIncidentTicketID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ClassificationIcon" ("Active" boolean, "id" integer primary key, "Description" varchar(100), "Name" varchar(35), "RelativeUrl" varchar(100), "System" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ClientPortalUser" ("ClientPortalActive" boolean, "id" integer primary key, "ContactID" integer, "DateFormat" integer, "NumberFormat" integer, "Password" varchar(50), "SecurityLevel" integer, "TimeFormat" integer, "UserName" varchar(200), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Contact" ("Active" integer, "AdditionalAddressInformation" varchar(100), "BulkEmailOptOut" boolean, "BulkEmailOptOutTime" timestamp without time zone, "AccountID" integer, "AddressLine" varchar(128), "AddressLine1" varchar(128), "AlternatePhone" varchar(32), "City" varchar(32), "Country" varchar(100), "CountryID" integer, "FaxNumber" varchar(25), "id" integer primary key, "MobilePhone" varchar(25), "Phone" varchar(25), "Extension" varchar(10), "State" varchar(40), "ZipCode" varchar(16), "CreateDate" timestamp without time zone, "EMailAddress" varchar(254), "EMailAddress2" varchar(254), "EMailAddress3" varchar(254), "ExternalID" varchar(50), "FacebookUrl" varchar(200), "FirstName" varchar(50), "LastActivityDate" timestamp without time zone, "LastModifiedDate" timestamp without time zone, "LastName" varchar(50), "LinkedInUrl" varchar(200), "MiddleInitial" varchar(2), "NamePrefix" integer, "NameSuffix" integer, "Note" varchar(50), "Notification" boolean, "PrimaryContact" boolean, "RoomNumber" varchar(50), "SurveyOptOut" boolean, "Title" varchar(50), "TwitterUrl" varchar(200), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Contract" ("BillingPreference" integer, "ContractCategory" integer, "AccountID" integer, "ContactID" integer, "Compliance" boolean, "ContactName" varchar(250), "id" integer primary key, "ContractName" varchar(100), "ContractNumber" varchar(50), "OverageBillingRate" real, "ContractPeriodType" varchar(1), "SetupFee" real, "SetupFeeAllocationCodeID" bigint, "ContractType" integer, "IsDefaultContract" boolean, "Description" varchar(2000), "EndDate" timestamp without time zone, "EstimatedCost" real, "EstimatedHours" real, "EstimatedRevenue" real, "ExclusionContractID" bigint, "InternalCurrencyOverageBillingRate" real, "InternalCurrencySetupFee" real, "RenewedContractID" bigint, "ServiceLevelAgreementID" integer, "StartDate" timestamp without time zone, "Status" integer, "TimeReportingRequiresStartAndStopTimes" integer, "OpportunityID" integer, "PurchaseOrderNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractBlock" ("ContractID" integer, "DatePurchased" timestamp without time zone, "EndDate" timestamp without time zone, "Hours" real, "HoursApproved" real, "InvoiceNumber" varchar(50), "IsPaid" varchar(10), "PaymentNumber" varchar(50), "HourlyRate" real, "StartDate" timestamp without time zone, "Status" integer, "id" integer primary key, "PaymentType" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractCost" ("AllocationCodeID" bigint, "BillableAmount" real, "BillableToAccount" boolean, "Billed" boolean, "ContractID" bigint, "ContractServiceBundleID" bigint, "ContractServiceID" bigint, "CostType" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" bigint, "DatePurchased" timestamp without time zone, "Description" varchar(2000), "ExtendedCost" real, "InternalCurrencyBillableAmount" real, "InternalCurrencyUnitPrice" real, "InternalPurchaseOrderNumber" varchar(50), "StatusLastModifiedBy" bigint, "StatusLastModifiedDate" timestamp without time zone, "Name" varchar(100), "ProductID" bigint, "PurchaseOrderNumber" varchar(50), "Status" bigint, "UnitCost" real, "UnitPrice" real, "UnitQuantity" real, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractExclusionAllocationCode" ("AllocationCodeID" bigint, "ContractID" bigint, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractExclusionRole" ("ContractID" bigint, "id" integer primary key, "RoleID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractFactor" ("ContractID" integer, "BlockHourFactor" real, "RoleID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractMilestone" ("AllocationCodeID" integer, "Amount" real, "ContractID" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" integer, "DateDue" timestamp without time zone, "Description" varchar(250), "InternalCurrencyAmount" real, "IsInitialPayment" boolean, "Status" integer, "Title" varchar(50), "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractNote" ("ContractID" varchar(25), "CreatorResourceID" integer, "Description" varchar(8000), "LastActivityDate" timestamp without time zone, "Title" varchar(250), "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractRate" ("ContractID" integer, "InternalCurrencyContractHourlyRate" real, "ContractHourlyRate" real, "RoleID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractRetainer" ("Amount" real, "AmountApproved" real, "ContractID" integer, "DatePurchased" timestamp without time zone, "EndDate" timestamp without time zone, "InternalCurrencyAmount" real, "InternalCurrencyAmountApproved" real, "InvoiceNumber" varchar(50), "IsPaid" integer, "paymentID" integer, "PaymentNumber" varchar(50), "StartDate" timestamp without time zone, "Status" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractRoleCost" ("ContractID" integer, "Rate" real, "ResourceID" integer, "RoleID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractService" ("AdjustedPrice" real, "ContractID" integer, "id" integer primary key, "InternalCurrencyAdjustedPrice" real, "InternalCurrencyUnitPrice" real, "InternalDescription" varchar(100), "InvoiceDescription" varchar(1000), "QuoteItemID" bigint, "ServiceID" integer, "UnitPrice" real, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractServiceAdjustment" ("AdjustedUnitCost" real, "AdjustedUnitPrice" real, "AllowRepeatService" boolean, "ContractServiceID" integer, "ContractID" integer, "QuoteItemID" integer, "ServiceID" integer, "EffectiveDate" timestamp without time zone, "UnitChange" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractServiceBundle" ("AdjustedPrice" real, "ContractID" integer, "id" integer primary key, "InternalCurrencyAdjustedPrice" real, "InternalCurrencyUnitPrice" real, "InternalDescription" varchar(100), "InvoiceDescription" varchar(1000), "QuoteItemID" bigint, "ServiceBundleID" integer, "UnitPrice" real, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractServiceBundleAdjustment" ("AdjustedUnitPrice" real, "AllowRepeatServiceBundle" boolean, "ContractServiceBundleID" integer, "ContractID" integer, "QuoteItemID" integer, "ServiceBundleID" integer, "EffectiveDate" timestamp without time zone, "UnitChange" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractServiceBundleUnit" ("Cost" real, "ContractServiceBundleID" integer, "InternalCurrencyPrice" real, "ApproveAndPostDate" timestamp without time zone, "ContractID" integer, "StartDate" timestamp without time zone, "EndDate" timestamp without time zone, "Price" real, "id" integer primary key, "ServiceBundleID" integer, "Units" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractServiceUnit" ("ContractServiceID" integer, "ContractID" integer, "EndDate" timestamp without time zone, "InternalCurrencyPrice" real, "Cost" real, "Price" real, "ServiceID" integer, "StartDate" timestamp without time zone, "Units" integer, "VendorAccountID" integer, "ApproveAndPostDate" timestamp without time zone, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ContractTicketPurchase" ("ContractID" bigint, "DatePurchased" timestamp without time zone, "EndDate" timestamp without time zone, "InvoiceNumber" varchar(50), "IsPaid" boolean, "PaymentNumber" varchar(50), "PaymentType" integer, "PerTicketRate" real, "StartDate" timestamp without time zone, "Status" integer, "TicketsPurchased" real, "TicketsUsed" real, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Country" ("Active" boolean, "AddressFormatID" bigint, "CountryCode" varchar(2), "id" integer primary key, "IsDefaultCountry" boolean, "DisplayName" varchar(100), "Name" varchar(50), "InvoiceTemplateID" integer, "QuoteTemplateID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Currency" ("Active" boolean, "Description" varchar(100), "id" integer primary key, "Name" varchar(3), "CurrencyNegativeFormat" varchar(10), "CurrencyPositiveFormat" varchar(10), "DisplaySymbol" integer, "ExchangeRate" real, "IsInternalCurrency" boolean, "LastModifiedDateTime" timestamp without time zone, "UpdateResourceId" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Department" ("id" integer primary key, "Description" varchar(1000), "Name" varchar(100), "Number" varchar(50), "PrimaryLocationID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ExpenseItem" ("AccountID" integer, "BillableToAccount" boolean, "ExpenseCurrencyID" integer, "Description" varchar(128), "Destination" varchar(128), "EntertainmentLocation" varchar(128), "ExpenseAmount" real, "ExpenseCategory" integer, "ExpenseDate" timestamp without time zone, "id" integer primary key, "ExpenseReportID" integer, "GLCode" varchar(20), "HaveReceipt" boolean, "Miles" real, "OdometerEnd" real, "OdometerStart" real, "Origin" varchar(128), "PaymentType" integer, "ProjectID" integer, "ReceiptAmount" real, "Reimbursable" boolean, "Rejected" boolean, "TaskID" integer, "TicketID" integer, "WorkType" integer, "PurchaseOrderNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ExpenseReport" ("AmountDue" real, "ApprovedDate" timestamp without time zone, "ApproverID" integer, "CashAdvanceAmount" real, "DepartmentNumber" varchar(50), "id" integer primary key, "ExpenseTotal" real, "Name" varchar(100), "WeekEnding" timestamp without time zone, "QuickBooksReferenceNumber" varchar(100), "RejectionReason" varchar(2048), "Status" integer, "Submit" boolean, "SubmitDate" timestamp without time zone, "SubmitterID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InstalledProduct" ("CreateDate" timestamp without time zone, "AccountID" integer, "DailyCost" real, "HourlyCost" real, "id" integer primary key, "MonthlyCost" real, "Notes" varchar(5000), "NumberOfUsers" real, "PerUseCost" real, "SetupFee" real, "Type" integer, "ContactID" integer, "ContractID" integer, "ContractServiceBundleID" integer, "ContractServiceID" integer, "InstallDate" timestamp without time zone, "InstalledByContactID" integer, "InstalledByID" integer, "LastModifiedTime" timestamp without time zone, "Location" varchar(100), "ParentInstalledProductID" integer, "Active" boolean, "ProductID" integer, "ReferenceNumber" varchar(50), "ReferenceTitle" varchar(200), "SerialNumber" varchar(100), "ServiceBundleID" integer, "ServiceID" integer, "ServiceLevelAgreementID" integer, "VendorID" integer, "WarrantyExpirationDate" timestamp without time zone, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InstalledProductType" ("Active" boolean, "id" integer primary key, "Name" varchar(100), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InstalledProductTypeUdfAssociation" ("id" integer primary key, "InstalledProductTypeId" bigint, "Required" boolean, "SortOrder" integer, "UserDefinedFieldDefinitionId" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InternalLocation" ("AdditionalAddressInfo" varchar(100), "Address1" varchar(100), "Address2" varchar(100), "City" varchar(50), "Country" varchar(100), "HolidaySetId" bigint, "id" integer primary key, "IsDefault" boolean, "Name" varchar(100), "State" varchar(25), "TimeZone" varchar(100), "PostalCode" varchar(20), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InventoryItem" ("BackOrder" integer, "Bin" varchar(50), "id" integer primary key, "InventoryLocationID" integer, "OnOrder" integer, "Picked" integer, "ProductID" integer, "QuantityMaximum" integer, "QuantityMinimum" integer, "QuantityOnHand" integer, "ReferenceNumber" varchar(50), "Reserved" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InventoryItemSerialNumber" ("InventoryItemID" bigint, "id" integer primary key, "SerialNumber" varchar(100), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InventoryLocation" ("Active" boolean, "IsDefault" boolean, "LocationName" varchar(50), "id" integer primary key, "ResourceID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InventoryTransfer" ("id" integer primary key, "Notes" varchar(4000), "ProductID" bigint, "QuantityTransferred" integer, "SerialNumber" varchar(100), "TransferByResourceID" integer, "TransferDate" timestamp without time zone, "FromLocationID" bigint, "ToLocationID" bigint, "UpdateNote" varchar(500), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Invoice" ("BatchID" integer, "AccountID" integer, "Comments" varchar(4000), "CreateDateTime" timestamp without time zone, "CreatorResourceID" integer, "DueDate" timestamp without time zone, "FromDate" timestamp without time zone, "InvoiceDateTime" timestamp without time zone, "InvoiceEditorTemplateID" integer, "id" integer primary key, "InvoiceNumber" varchar(100), "InvoiceTotal" real, "IsVoided" boolean, "OrderNumber" varchar(20), "PaidDate" timestamp without time zone, "PaymentTerm" integer, "TaxGroup" integer, "TaxRegionName" varchar(200), "ToDate" timestamp without time zone, "TotalTaxValue" real, "VoidedByResourceID" integer, "VoidedDate" timestamp without time zone, "WebServiceDate" timestamp without time zone, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_InvoiceTemplate" ("CoveredByBlockRetainerContractLabel" varchar(50), "CoveredByRecurringServiceFixedPricePerTicketContractLabel" varchar(50), "CurrencyNegativeFormat" varchar(10), "CurrencyPositiveFormat" varchar(10), "DateFormat" integer, "DisplayFixedPriceContractLabor" boolean, "DisplayRecurringServiceContractLabor" boolean, "PageNumberFormat" integer, "DisplaySeparateLineItemForEachTax" boolean, "DisplayTaxCategory" boolean, "DisplayTaxCategorySuperscripts" boolean, "DisplayZeroAmountRecurringServicesAndBundles" boolean, "GroupBy" integer, "id" integer primary key, "ItemizeItemsInEachGroup" integer, "ItemizeServicesAndBundles" boolean, "Name" varchar(50), "NonBillableLaborLabel" varchar(50), "NumberFormat" integer, "PageLayout" integer, "PaymentTerms" integer, "RateCostExpression" varchar(50), "ShowGridHeader" boolean, "ShowVerticalGridLines" boolean, "SortBy" integer, "TimeFormat" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_NotificationHistory" ("AccountID" bigint, "EntityNumber" varchar(50), "EntityTitle" varchar(2000), "id" integer primary key, "InitiatingContactID" bigint, "InitiatingResourceID" bigint, "IsActive" boolean, "IsDeleted" boolean, "IsTemplateJob" boolean, "NotificationHistoryTypeID" integer, "NotificationSentTime" timestamp without time zone, "OpportunityID" bigint, "ProjectID" bigint, "QuoteID" bigint, "RecipientDisplayName" varchar(200), "RecipientEmailAddress" varchar(2000), "TaskID" bigint, "TemplateName" varchar(100), "TicketID" bigint, "TimeEntryID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Opportunity" ("AccountID" integer, "Amount" real, "AssessmentScore" real, "Barriers" varchar(500), "ClosedDate" timestamp without time zone, "ContactID" integer, "Cost" real, "CreateDate" timestamp without time zone, "OwnerResourceID" integer, "AdvancedField4" real, "DateStamp" timestamp without time zone, "Title" varchar(128), "HelpNeeded" varchar(500), "AdvancedField3" real, "LastActivity" timestamp without time zone, "LeadReferral" integer, "LossReason" integer, "LossReasonDetail" varchar(500), "Market" varchar(500), "MonthlyCost" real, "MonthlyRevenue" real, "AdvancedField5" real, "NextStep" varchar(500), "AdvancedField1" real, "OnetimeCost" real, "OnetimeRevenue" real, "id" integer primary key, "PrimaryCompetitor" integer, "Probability" integer, "ProductID" integer, "ProjectedCloseDate" timestamp without time zone, "QuarterlyCost" real, "QuarterlyRevenue" real, "RelationshipAssessmentScore" real, "RevenueSpread" integer, "SalesOrderID" integer, "SalesProcessPercentComplete" integer, "SemiannualCost" real, "SemiannualRevenue" real, "AdvancedField2" real, "Stage" integer, "ProjectedLiveDate" timestamp without time zone, "Status" integer, "TechnicalAssessmentScore" real, "ThroughDate" timestamp without time zone, "TotalAmountMonths" integer, "UseQuoteTotals" boolean, "WinReason" integer, "WinReasonDetail" varchar(500), "YearlyCost" real, "YearlyRevenue" real, "Rating" integer, "PromotionName" varchar(50), "RevenueSpreadUnit" varchar(1), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PaymentTerm" ("Active" boolean, "Description" varchar(2000), "Name" varchar(100), "PaymentDueInDays" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Phase" ("Scheduled" boolean, "ParentPhaseID" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" integer, "Description" varchar(8000), "DueDate" timestamp without time zone, "EstimatedHours" real, "ExternalID" varchar(50), "id" integer primary key, "LastActivityDateTime" timestamp without time zone, "PhaseNumber" varchar(50), "StartDate" timestamp without time zone, "Title" varchar(255), "ProjectID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListMaterialCode" ("AllocationCodeID" integer, "CurrencyID" integer, "id" integer primary key, "UnitPrice" real, "UsesInternalCurrencyPrice" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListProduct" ("CurrencyID" integer, "id" integer primary key, "ProductID" integer, "UnitPrice" real, "UsesInternalCurrencyPrice" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListRole" ("CurrencyID" integer, "HourlyRate" real, "id" integer primary key, "RoleID" integer, "UsesInternalCurrencyPrice" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListService" ("CurrencyID" integer, "id" integer primary key, "ServiceID" integer, "UnitPrice" real, "UsesInternalCurrencyPrice" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListServiceBundle" ("CurrencyID" integer, "id" integer primary key, "ServiceBundleID" integer, "UnitPrice" real, "UsesInternalCurrencyPrice" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PriceListWorkTypeModifier" ("CurrencyID" integer, "id" integer primary key, "ModifierType" integer, "UsesInternalCurrencyPrice" boolean, "ModifierValue" real, "WorkTypeModifierID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Product" ("Active" boolean, "ProductAllocationCodeID" integer, "CostAllocationCodeID" integer, "DoesNotRequireProcurement" boolean, "ExternalProductID" varchar(50), "InternalProductID" varchar(50), "Serialized" boolean, "MSRP" real, "ManufacturerName" varchar(100), "ManufacturerProductName" varchar(50), "PeriodType" varchar(10), "ProductCategory" integer, "Description" varchar(2000), "Link" varchar(500), "Name" varchar(100), "SKU" varchar(50), "id" integer primary key, "UnitCost" real, "UnitPrice" real, "DefaultVendorID" integer, "VendorProductNumber" varchar(50), "MarkupRate" real, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ProductVendor" ("Active" boolean, "IsDefault" boolean, "ProductID" integer, "VendorID" integer, "VendorCost" real, "VendorPartNumber" varchar(50), "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Project" ("AccountID" integer, "CompanyOwnerResourceID" integer, "ActualBilledHours" real, "ActualHours" real, "ChangeOrdersRevenue" real, "ChangeOrdersBudget" real, "CompletedPercentage" integer, "CompletedDateTime" timestamp without time zone, "ContractID" integer, "CreatorResourceID" integer, "CreateDateTime" timestamp without time zone, "Department" integer, "Description" varchar(2000), "Duration" integer, "EndDateTime" timestamp without time zone, "EstimatedSalesCost" real, "EstimatedTime" real, "ExtPNumber" varchar(50), "ExtProjectType" integer, "LaborEstimatedCosts" real, "LaborEstimatedMarginPercentage" real, "LaborEstimatedRevenue" real, "LineOfBusiness" integer, "OriginalEstimatedRevenue" real, "ProjectCostEstimatedMarginPercentage" real, "ProjectCostsRevenue" real, "ProjectCostsBudget" real, "ProjectLeadResourceID" integer, "ProjectName" varchar(100), "ProjectNumber" varchar(50), "SGDA" real, "StartDateTime" timestamp without time zone, "Status" integer, "StatusDateTime" timestamp without time zone, "StatusDetail" varchar(2000), "Type" integer, "id" integer primary key, "PurchaseOrderNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ProjectCost" ("AllocationCodeID" bigint, "BillableAmount" real, "BillableToAccount" boolean, "Billed" boolean, "ContractServiceBundleID" bigint, "ContractServiceID" bigint, "CostType" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" bigint, "DatePurchased" timestamp without time zone, "Description" varchar(2000), "EstimatedCost" real, "ExtendedCost" real, "InternalCurrencyBillableAmount" real, "InternalCurrencyUnitPrice" real, "InternalPurchaseOrderNumber" varchar(50), "StatusLastModifiedBy" bigint, "StatusLastModifiedDate" timestamp without time zone, "Name" varchar(100), "ProductID" bigint, "ProjectID" bigint, "PurchaseOrderNumber" varchar(50), "Status" bigint, "UnitCost" real, "UnitPrice" real, "UnitQuantity" real, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ProjectNote" ("Announce" boolean, "CreatorResourceID" integer, "Description" varchar(32000), "LastActivityDate" timestamp without time zone, "NoteType" integer, "ProjectID" integer, "Publish" integer, "id" integer primary key, "Title" varchar(250), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PurchaseOrder" ("ShipToAddress1" varchar(128), "ShipToAddress2" varchar(128), "ShipToName" varchar(100), "CancelDateTime" timestamp without time zone, "ShipToCity" varchar(30), "CreateDateTime" timestamp without time zone, "CreatorResourceID" integer, "ShippingDate" timestamp without time zone, "ExternalPONumber" varchar(50), "Fax" varchar(25), "Freight" real, "GeneralMemo" varchar(4000), "LatestEstimatedArrivalDate" timestamp without time zone, "id" integer primary key, "Status" integer, "PaymentTerm" integer, "Phone" varchar(25), "ShipToPostalCode" varchar(10), "PurchaseForAccountID" integer, "ShippingType" integer, "ShowEachTaxInGroup" boolean, "ShowTaxCategory" boolean, "ShipToState" varchar(25), "SubmitDateTime" timestamp without time zone, "TaxGroup" integer, "UseItemDescriptionsFrom" integer, "VendorID" integer, "VendorInvoiceNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PurchaseOrderItem" ("ContractID" bigint, "CostID" integer, "EstimatedArrivalDate" timestamp without time zone, "id" integer primary key, "InventoryLocationID" integer, "OrderID" integer, "Memo" varchar(4000), "ProductID" integer, "UnitCost" real, "ProjectID" bigint, "Quantity" integer, "SalesOrderID" bigint, "TicketID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_PurchaseOrderReceive" ("id" integer primary key, "PurchaseOrderItemID" bigint, "QuantityBackOrdered" integer, "QuantityNowReceiving" integer, "QuantityPreviouslyReceived" integer, "ReceiveDate" timestamp without time zone, "SerialNumber" varchar(50), "ReceivedByResourceID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Quote" ("AccountID" integer, "GroupByID" integer, "LastActivityDate" timestamp without time zone, "LastModifiedBy" integer, "QuoteNumber" integer, "QuoteTemplateID" integer, "ShowTaxCategory" boolean, "BillToLocationID" integer, "CalculateTaxSeparately" boolean, "ContactID" integer, "CreatorResourceID" integer, "CreateDate" timestamp without time zone, "EffectiveDate" timestamp without time zone, "eQuoteActive" boolean, "ExpirationDate" timestamp without time zone, "ExternalQuoteNumber" varchar(50), "GroupByProductCategory" boolean, "PrimaryQuote" boolean, "OpportunityID" integer, "PaymentTerm" integer, "PaymentType" integer, "ProposalProjectID" integer, "PurchaseOrderNumber" varchar(50), "Comment" varchar(1000), "Description" varchar(2000), "id" integer primary key, "Name" varchar(100), "ShipToLocationID" integer, "ShippingType" integer, "ShowEachTaxInGroup" boolean, "SoldToLocationID" integer, "TaxGroup" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_QuoteItem" ("AverageCost" real, "CostID" integer, "UnitDiscount" real, "PercentageDiscount" real, "ExpenseID" integer, "HighestCost" real, "InternalCurrencyUnitDiscount" real, "InternalCurrencyLineDiscount" real, "InternalCurrencyUnitPrice" real, "LaborID" integer, "LineDiscount" real, "MarkupRate" real, "IsOptional" boolean, "Type" integer, "PeriodType" varchar(50), "ProductID" integer, "Quantity" real, "QuoteID" integer, "Description" varchar(2000), "id" integer primary key, "Name" varchar(100), "ServiceBundleID" integer, "ServiceID" integer, "ShippingID" integer, "TaxCategoryID" integer, "TotalEffectiveTax" real, "IsTaxable" boolean, "UnitCost" real, "UnitPrice" real, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_QuoteLocation" ("Address1" varchar(50), "Address2" varchar(50), "City" varchar(50), "id" integer primary key, "PostalCode" varchar(20), "State" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_QuoteTemplate" ("Active" boolean, "CalculateTaxSeparately" boolean, "CreateDate" timestamp without time zone, "CreatedBy" integer, "CurrencyNegativeFormat" varchar(10), "CurrencyPositiveFormat" varchar(10), "DateFormat" integer, "Description" varchar(200), "DisplayCurrencySymbol" integer, "DisplayTaxCategorySuperscripts" boolean, "id" integer primary key, "LastActivityBy" integer, "LastActivityDate" timestamp without time zone, "Name" varchar(50), "NumberFormat" integer, "PageLayout" integer, "PageNumberFormat" integer, "ShowEachTaxInGroup" boolean, "ShowGridHeader" boolean, "ShowTaxCategory" boolean, "ShowVerticalGridLines" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Resource" ("AccountingReferenceID" varchar(100), "Email2" varchar(254), "EmailTypeCode2" varchar(20), "Email3" varchar(254), "EmailTypeCode3" varchar(20), "DateFormat" varchar(20), "DefaultServiceDeskRoleID" bigint, "Email" varchar(254), "EmailTypeCode" varchar(20), "FirstName" varchar(50), "Gender" varchar(1), "Greeting" integer, "HireDate" timestamp without time zone, "HomePhone" varchar(25), "InternalCost" real, "LastName" varchar(50), "MiddleName" varchar(50), "MobilePhone" varchar(25), "NumberFormat" varchar(20), "OfficeExtension" varchar(10), "OfficePhone" varchar(25), "Password" varchar(50), "Initials" varchar(32), "PayrollType" integer, "LocationID" integer, "id" integer primary key, "ResourceType" varchar(15), "Active" boolean, "Suffix" varchar(10), "TimeFormat" varchar(20), "Title" varchar(50), "TravelAvailabilityPct" varchar(15), "UserType" integer, "UserName" varchar(32), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ResourceRole" ("Active" boolean, "DepartmentID" bigint, "id" integer primary key, "QueueID" bigint, "ResourceID" bigint, "RoleID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ResourceSkill" ("id" integer primary key, "ResourceID" bigint, "SkillDescription" varchar(2000), "SkillID" bigint, "SkillLevel" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Role" ("Active" boolean, "Description" varchar(200), "HourlyFactor" real, "HourlyRate" real, "IsExcludedFromNewContracts" boolean, "Name" varchar(200), "QuoteItemDefaultTaxCategoryId" integer, "id" integer primary key, "RoleType" integer, "SystemRole" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_SalesOrder" ("AdditionalBillToAddressInformation" varchar(100), "AdditionalShipToAddressInformation" varchar(100), "BillToCountryID" integer, "BillToAddress1" varchar(150), "BillToAddress2" varchar(150), "BillToCity" varchar(50), "BillToCountry" varchar(100), "BillToState" varchar(50), "BillToPostalCode" varchar(50), "AccountID" integer, "Contact" integer, "OpportunityID" integer, "OwnerResourceID" integer, "PromisedDueDate" timestamp without time zone, "SalesOrderDate" timestamp without time zone, "id" integer primary key, "ShipToCountryID" integer, "ShipToAddress1" varchar(150), "ShipToAddress2" varchar(150), "ShipToCity" varchar(50), "ShipToCountry" varchar(100), "ShipToState" varchar(50), "ShipToPostalCode" varchar(50), "Status" integer, "Title" varchar(128), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Service" ("InvoiceDescription" varchar(1000), "MarkupRate" real, "ServiceLevelAgreementID" bigint, "UnitCost" real, "VendorAccountID" integer, "IsActive" boolean, "AllocationCodeID" integer, "CreatorResourceID" integer, "CreateDate" timestamp without time zone, "PeriodType" varchar(1), "Description" varchar(400), "id" integer primary key, "Name" varchar(100), "UnitPrice" real, "UpdateResourceID" integer, "LastModifiedDate" timestamp without time zone, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceBundle" ("InvoiceDescription" varchar(1000), "ServiceLevelAgreementID" bigint, "UnitCost" real, "IsActive" boolean, "AllocationCodeID" integer, "CreatorResourceID" integer, "CreateDate" timestamp without time zone, "UnitDiscount" real, "PercentageDiscount" real, "PeriodType" varchar(1), "Description" varchar(200), "id" integer primary key, "Name" varchar(100), "UnitPrice" real, "UpdateResourceID" integer, "LastModifiedDate" timestamp without time zone, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceBundleService" ("ServiceBundleID" bigint, "id" integer primary key, "ServiceID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceCall" ("CancelationNoticeHours" real, "CanceledByResource" integer, "CanceledDateTime" timestamp without time zone, "AccountID" integer, "Complete" smallint, "CreateDateTime" timestamp without time zone, "CreatorResourceID" integer, "Description" varchar(2000), "Duration" real, "EndDateTime" timestamp without time zone, "LastModifiedDateTime" timestamp without time zone, "id" integer primary key, "StartDateTime" timestamp without time zone, "Status" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceCallTask" ("ServiceCallID" integer, "id" integer primary key, "TaskID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceCallTaskResource" ("id" integer primary key, "ResourceID" integer, "ServiceCallTaskID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceCallTicket" ("ServiceCallID" integer, "id" integer primary key, "TicketID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ServiceCallTicketResource" ("id" integer primary key, "ResourceID" integer, "ServiceCallTicketID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_ShippingType" ("AllocationCodeID" integer, "IsActive" boolean, "Description" varchar(2000), "id" integer primary key, "Name" varchar(100), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Skill" ("Active" boolean, "CategoryID" bigint, "Description" varchar(2000), "Name" varchar(100), "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Subscription" ("Description" varchar(2000), "EffectiveDate" timestamp without time zone, "ExpirationDate" timestamp without time zone, "InstalledProductID" integer, "MaterialCodeID" integer, "PeriodCost" real, "PeriodPrice" real, "PeriodType" varchar(1), "PurchaseOrderNumber" varchar(50), "id" integer primary key, "SubscriptionName" varchar(100), "TotalCost" real, "TotalPrice" real, "Status" integer, "VendorID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_SubscriptionPeriod" ("PeriodCost" real, "PeriodDate" timestamp without time zone, "PeriodPrice" real, "PostedDate" timestamp without time zone, "PurchaseOrderNumber" varchar(50), "SubscriptionID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Task" ("AllocationCodeID" integer, "CanClientPortalUserCompleteTask" boolean, "HoursToBeScheduled" real, "IsVisibleInClientPortal" boolean, "PhaseID" integer, "ProjectID" integer, "PurchaseOrderNumber" varchar(50), "RemainingHours" real, "AssignedResourceID" integer, "AssignedResourceRoleID" integer, "TaskIsBillable" boolean, "CompletedDateTime" timestamp without time zone, "CreateDateTime" timestamp without time zone, "CreatorResourceID" integer, "DepartmentID" integer, "Description" varchar(8000), "EndDateTime" timestamp without time zone, "EstimatedHours" real, "ExternalID" varchar(50), "id" integer primary key, "LastActivityDateTime" timestamp without time zone, "TaskNumber" varchar(50), "Priority" integer, "StartDateTime" timestamp without time zone, "Status" integer, "Title" varchar(255), "TaskType" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TaskNote" ("CreatorResourceID" integer, "Description" varchar(32000), "LastActivityDate" timestamp without time zone, "NoteType" integer, "Publish" integer, "TaskID" integer, "id" integer primary key, "Title" varchar(250), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TaskPredecessor" ("LagDays" integer, "PredecessorTaskID" integer, "SuccessorTaskID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TaskSecondaryResource" ("ResourceID" integer, "RoleID" integer, "id" integer primary key, "TaskID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Tax" ("IsCompounded" boolean, "TaxCategoryID" integer, "id" integer primary key, "TaxName" varchar(100), "TaxRate" real, "TaxRegionID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TaxCategory" ("Active" boolean, "Description" varchar(200), "id" integer primary key, "Name" varchar(200), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TaxRegion" ("Active" boolean, "id" integer primary key, "Name" varchar(200), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_Ticket" ("AEMAlertID" varchar(50), "AllocationCodeID" integer, "ChangeApprovalBoard" integer, "ChangeApprovalStatus" integer, "ChangeApprovalType" integer, "ChangeInfoField1" varchar(8000), "ChangeInfoField2" varchar(8000), "ChangeInfoField3" varchar(8000), "ChangeInfoField4" varchar(8000), "ChangeInfoField5" varchar(8000), "AccountID" integer, "InstalledProductID" integer, "ContractID" integer, "ContractServiceBundleID" bigint, "ContractServiceID" bigint, "FirstResponseAssignedResourceID" integer, "FirstResponseDateTime" timestamp without time zone, "FirstResponseDueDateTime" timestamp without time zone, "FirstResponseInitiatingResourceID" integer, "ServiceLevelAgreementHasBeenMet" boolean, "HoursToBeScheduled" real, "LastCustomerNotificationDateTime" timestamp without time zone, "LastCustomerVisibleActivityDateTime" timestamp without time zone, "MonitorID" integer, "MonitorTypeID" integer, "OpportunityId" integer, "ProblemTicketId" integer, "ProjectID" integer, "Resolution" varchar(32000), "ResolutionPlanDateTime" timestamp without time zone, "ResolutionPlanDueDateTime" timestamp without time zone, "ResolvedDateTime" timestamp without time zone, "ResolvedDueDateTime" timestamp without time zone, "AssignedResourceID" integer, "AssignedResourceRoleID" integer, "ServiceLevelAgreementID" integer, "TicketCategory" integer, "ContactID" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" integer, "CompletedDate" timestamp without time zone, "QueueID" integer, "Description" varchar(8000), "DueDateTime" timestamp without time zone, "EstimatedHours" real, "ExternalID" varchar(50), "id" integer primary key, "IssueType" integer, "LastActivityDate" timestamp without time zone, "TicketNumber" varchar(50), "Priority" integer, "Source" integer, "Status" integer, "SubIssueType" integer, "Title" varchar(255), "TicketType" integer, "PurchaseOrderNumber" varchar(50), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TicketAdditionalContact" ("ContactID" integer, "id" integer primary key, "TicketID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TicketChangeRequestApproval" ("ApproveRejectDateTime" timestamp without time zone, "ApproveRejectNote" varchar(2000), "id" integer primary key, "ContactID" integer, "IsApproved" boolean, "ResourceID" integer, "TicketID" integer, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TicketCost" ("AllocationCodeID" bigint, "BillableAmount" real, "BillableToAccount" boolean, "Billed" boolean, "ContractServiceBundleID" bigint, "ContractServiceID" bigint, "CostType" integer, "CreateDate" timestamp without time zone, "CreatorResourceID" bigint, "DatePurchased" timestamp without time zone, "Description" varchar(2000), "ExtendedCost" real, "InternalCurrencyBillableAmount" real, "InternalCurrencyUnitPrice" real, "InternalPurchaseOrderNumber" varchar(50), "StatusLastModifiedBy" bigint, "StatusLastModifiedDate" timestamp without time zone, "Name" varchar(100), "ProductID" bigint, "PurchaseOrderNumber" varchar(50), "Status" bigint, "TicketID" bigint, "UnitCost" real, "UnitPrice" real, "UnitQuantity" real, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TicketNote" ("CreatorResourceID" integer, "Description" varchar(32000), "LastActivityDate" timestamp without time zone, "NoteType" integer, "Publish" integer, "TicketID" integer, "id" integer primary key, "Title" varchar(250), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TicketSecondaryResource" ("id" integer primary key, "ResourceID" bigint, "RoleID" bigint, "TicketID" bigint, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_TimeEntry" ("AllocationCodeID" integer, "BillingApprovalDateTime" timestamp without time zone, "BillingApprovalLevelMostRecent" integer, "BillingApprovalResourceID" integer, "ContractID" integer, "ContractServiceBundleID" bigint, "ContractServiceID" bigint, "CreateDateTime" timestamp without time zone, "CreatorUserID" integer, "DateWorked" timestamp without time zone, "EndDateTime" timestamp without time zone, "HoursToBill" real, "HoursWorked" real, "InternalAllocationCodeID" integer, "InternalNotes" varchar(8000), "LastModifiedUserID" integer, "LastModifiedDateTime" timestamp without time zone, "NonBillable" boolean, "OffsetHours" real, "ResourceID" integer, "RoleID" integer, "ShowOnInvoice" boolean, "StartDateTime" timestamp without time zone, "SummaryNotes" varchar(8000), "TaskID" integer, "Type" integer, "TicketID" integer, "id" integer primary key, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_UserDefinedFieldDefinition" ("IsActive" boolean, "CreateDate" timestamp without time zone, "CrmToProjectUdfId" bigint, "DataType" integer, "DefaultValue" varchar(1024), "Description" varchar(128), "DisplayFormat" integer, "IsEncrypted" boolean, "IsFieldMapping" boolean, "id" integer primary key, "MergeVariableName" varchar(100), "Name" varchar(45), "NumberOfDecimalPlaces" integer, "IsProtected" boolean, "IsRequired" boolean, "SortOrder" integer, "UdfType" integer, "IsVisibleToClientPortal" boolean, UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_UserDefinedFieldListItem" ("CreateDate" timestamp without time zone, "id" integer primary key, "UdfFieldId" bigint, "ValueForDisplay" varchar(128), "ValueForExport" varchar(128), UserDefinedFields json, local_lastmodified timestamp without time zone);
create table "at_WorkTypeModifier" ("id" integer primary key, "ModifierType" integer, "ModifierValue" real, UserDefinedFields json, local_lastmodified timestamp without time zone);

-- 1 down
drop table if exists "at_Account";
drop table if exists "at_AccountAlert";
drop table if exists "at_AccountLocation";
drop table if exists "at_AccountNote";
drop table if exists "at_AccountTeam";
drop table if exists "at_AccountToDo";
drop table if exists "at_ActionType";
drop table if exists "at_AdditionalInvoiceFieldValue";
drop table if exists "at_AllocationCode";
drop table if exists "at_Appointment";
drop table if exists "at_AttachmentInfo";
drop table if exists "at_BillingItem";
drop table if exists "at_BillingItemApprovalLevel";
drop table if exists "at_ChangeRequestLink";
drop table if exists "at_ClassificationIcon";
drop table if exists "at_ClientPortalUser";
drop table if exists "at_Contact";
drop table if exists "at_Contract";
drop table if exists "at_ContractBlock";
drop table if exists "at_ContractCost";
drop table if exists "at_ContractExclusionAllocationCode";
drop table if exists "at_ContractExclusionRole";
drop table if exists "at_ContractFactor";
drop table if exists "at_ContractMilestone";
drop table if exists "at_ContractNote";
drop table if exists "at_ContractRate";
drop table if exists "at_ContractRetainer";
drop table if exists "at_ContractRoleCost";
drop table if exists "at_ContractService";
drop table if exists "at_ContractServiceAdjustment";
drop table if exists "at_ContractServiceBundle";
drop table if exists "at_ContractServiceBundleAdjustment";
drop table if exists "at_ContractServiceBundleUnit";
drop table if exists "at_ContractServiceUnit";
drop table if exists "at_ContractTicketPurchase";
drop table if exists "at_Country";
drop table if exists "at_Currency";
drop table if exists "at_Department";
drop table if exists "at_ExpenseItem";
drop table if exists "at_ExpenseReport";
drop table if exists "at_InstalledProduct";
drop table if exists "at_InstalledProductType";
drop table if exists "at_InstalledProductTypeUdfAssociation";
drop table if exists "at_InternalLocation";
drop table if exists "at_InventoryItem";
drop table if exists "at_InventoryItemSerialNumber";
drop table if exists "at_InventoryLocation";
drop table if exists "at_InventoryTransfer";
drop table if exists "at_Invoice";
drop table if exists "at_InvoiceTemplate";
drop table if exists "at_NotificationHistory";
drop table if exists "at_Opportunity";
drop table if exists "at_PaymentTerm";
drop table if exists "at_Phase";
drop table if exists "at_PriceListMaterialCode";
drop table if exists "at_PriceListProduct";
drop table if exists "at_PriceListRole";
drop table if exists "at_PriceListService";
drop table if exists "at_PriceListServiceBundle";
drop table if exists "at_PriceListWorkTypeModifier";
drop table if exists "at_Product";
drop table if exists "at_ProductVendor";
drop table if exists "at_Project";
drop table if exists "at_ProjectCost";
drop table if exists "at_ProjectNote";
drop table if exists "at_PurchaseOrder";
drop table if exists "at_PurchaseOrderItem";
drop table if exists "at_PurchaseOrderReceive";
drop table if exists "at_Quote";
drop table if exists "at_QuoteItem";
drop table if exists "at_QuoteLocation";
drop table if exists "at_QuoteTemplate";
drop table if exists "at_Resource";
drop table if exists "at_ResourceRole";
drop table if exists "at_ResourceSkill";
drop table if exists "at_Role";
drop table if exists "at_SalesOrder";
drop table if exists "at_Service";
drop table if exists "at_ServiceBundle";
drop table if exists "at_ServiceBundleService";
drop table if exists "at_ServiceCall";
drop table if exists "at_ServiceCallTask";
drop table if exists "at_ServiceCallTaskResource";
drop table if exists "at_ServiceCallTicket";
drop table if exists "at_ServiceCallTicketResource";
drop table if exists "at_ShippingType";
drop table if exists "at_Skill";
drop table if exists "at_Subscription";
drop table if exists "at_SubscriptionPeriod";
drop table if exists "at_Task";
drop table if exists "at_TaskNote";
drop table if exists "at_TaskPredecessor";
drop table if exists "at_TaskSecondaryResource";
drop table if exists "at_Tax";
drop table if exists "at_TaxCategory";
drop table if exists "at_TaxRegion";
drop table if exists "at_Ticket";
drop table if exists "at_TicketAdditionalContact";
drop table if exists "at_TicketChangeRequestApproval";
drop table if exists "at_TicketCost";
drop table if exists "at_TicketNote";
drop table if exists "at_TicketSecondaryResource";
drop table if exists "at_TimeEntry";
drop table if exists "at_UserDefinedFieldDefinition";
drop table if exists "at_UserDefinedFieldListItem";
drop table if exists "at_WorkTypeModifier";
